trailingComma: 'es5'
printWidth: 120
tabWidth: 4
semi: true
singleQuote: true
bracketSpacing: false
proseWrap: 'always'
overrides:
  - files: ['*.md', '*.json', '*.yml', '*.xml']
    options: {tabWidth: 2}
